name: docker build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the developpment branch
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -XPOST -u "${{ secrets.DISPATCH_USERNAME}}:${{secrets.DISPATCH_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/tygerlord/docker-domoticz-dev/actions/workflows/main.yml/dispatches --data '{"ref": "main"}'
